feat: add `run-dash` action to analyze 3rd party dependencies
eclipse-tractusx/sig-infra pull request #174
Opened 2023-07-18 08:49 UTC by SebastianBezold

## Description

This PR does add a new GitHub action, that is setting up the [Eclipse Dash](https://github.com/eclipse/dash-licenses) license tool. Based on a view config params, Dash will analyze the 3rd party dependencies and check, if the `DEPENDENCIES` file present in a repository is up-to-date.

Fixes #168

2023-07-18 08:55 UTC, almadigabor requested changes

2023-07-18 11:20 UTC, FaGru3n approved these changes
Great work looks easy to understand an will automate the Dash Licence Check 
<img src="https://media4.giphy.com/media/NytMLKyiaIh6VH9SPm/giphy.gif" width="200" height="200" />

suggested changes:
- i would only add an empty line in .github/actions/run-dash/action.yaml at the end

2023-07-18 13:17 UTC, SebastianBezold commented on .github/actions/run-dash/README.md
> +as-is. Therefor a minimal set of config for the `run-dash` action is needed.
Oh thx for pointing out :P fixed that

2023-07-19 07:09 UTC, almadigabor approved these changes
Way better to inform what's wrong with the file. I was wondering if it would be more useful to output a combined result like it's out of date & contains rejected & contains restricted.

2023-07-19 11:06 UTC, SebastianBezold commented
> Way better to inform what's wrong with the file. I was wondering if it would be more useful to output a combined result like it's out of date & contains rejected & contains restricted.

You actually could do both. Via input, you can configure when the action itself will fail, but the flags for that (out-of-date, contains restricted, contains rejected) are also available as output.
So you could configure it to never fail and evaluate the step output yourself

2023-07-19 11:06 UTC, merged